version: '3'

services:
  app:
    build:
      context: .
    container_name: vethub
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/vethub?currentSchema=vethub
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1564
    ports:
      - '8080:8080'
  db:
    image: postgres:15.1-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1564
      - POSTGRES_DB=vethub
    expose:
      - 5432
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d