spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vethub?currentSchema=vethub
    username: postgres
    password: 1564
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never
      continue-on-error: false
 #     data-locations: classpath:demo_data.sql
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: vethub

security:
  jwt:
    secret: QVdEQURXQURXQURBV0RXQURBV0RTQURDWlhDWFpDWFpDQVdEQVdEQVdEU0FDWFpDWkFXREFXREFTQ1haQ1haQ0FXREFTQUNaQw
    access: 2592000000 #3600000
    refresh: 2592000000

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
