spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vethub?currentSchema=vethub
    username: postgres
    password: 1564
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      continue-on-error: false
 #     data-locations: classpath:demo_data.sql

security:
  jwt:
    secret: aGZiYmtiYWllYmNpZWFpZWJsZWNldWNlY2xhZWNhaWJlbGNhZWN3Q0VCV0VXSUM=
    access: 3600000
    refresh: 2592000000

